### PR TITLE
format uid for users in contact search

### PR DESCRIPTION
**Pull request by danielljohnson**
Open Questions:

- Figure out a font with a slash, I tried a few that I found online but I'd need to import a font, worth it?

### CODE REVIEW

**Comment by evandana** [comment]
Will this fully address #152 ?

**Comment by evandana** [comment]
Can you drop a few snapshots into the PR description?

**Review by evandana — COMMENTED** [review]
Looks good so far! I'll pull this down and run it on my other computer before this evening.

**Comment by evandana** [comment]
Looks like there's one place where it needs to be updated and one where it could be updated
- Need: http://localhost:3000/contact/aaaa236889aaa/info
image

- Optional: 
image


## Looks good here
image
image
image

**Comment by danielljohnson** [comment]
@evandana I tried some regex stuff for the search-bar itself and I always end up with too many edge cases for it to be usable. There are libraries out there for input masking, but we'd have to find one that works with the old material UI autocomplete. For now, I'd vote to just merge what's here and create a new ticket for input masking if we want to try to tackle it later on as it's not a small task.

**Review by evandana — APPROVED** [review]
Fixed the requested issue by removing UID where it wasn't needed
image

**Comment by evandana** [comment]
@balancerockmedia Please create the ticket for formatting the UID as you type in the search bar before merging this.

**Pull request merged**
